#:schema node_modules/wrangler/config-schema.json
name = "travellings"
compatibility_date = "2024-11-01"
assets = { directory = "./.vitepress/dist" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
