name: Translate Docs

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
        - '/zh_TW/**'
        - '/en_US/**'
        - '/.github/**'

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencc requests

    - name: Run translation script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/scripts/docs_translate2tw.py

    - name: Comment on PR with translation suggestions
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Translation Suggestions
        path: translation_output.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
